CC=gcc


all:  readerV2 writerV2 writerV3 serverV3 clientV3

readerV2: readerV2.c
	$(CC)  -o readerV2 readerV2.c

writerV2: writerV2.c
	$(CC)  -o writerV2 writerV2.c

writerV3: writerV3.c
	$(CC)  -o writerV3 writerV3.c

serverV3: serverV3.c
	$(CC)  -o serverV3 serverV3.c

clientV3: clientV3.c
	$(CC)  -o clientV3 clientV3.c

clean:
	rm -f  clientV1 serverV1 readerV2 writerV2 writerV3 serverV3 clientV3
